package CRUD;

import Configuracion_Conexion.Conecc;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
public class FrmCliente extends javax.swing.JInternalFrame {

    PreparedStatement Stand;
    ResultSet RestSet;
    ResultSetMetaData Meta;

    /**
     * Creates new form FrmCliente
     */
    public FrmCliente() {
        initComponents();
        Load ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablon = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        INP_Codigo = new javax.swing.JTextField();
        INP_Nombre = new javax.swing.JTextField();
        INP_Apellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        INP_Balance = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BTN_Registrar = new javax.swing.JToggleButton();
        BTN_Modificar = new javax.swing.JToggleButton();
        BTN_Delete = new javax.swing.JToggleButton();
        BTN_Cargar = new javax.swing.JButton();
        BTN_Salir1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Registro de Cuenta");

        Tablon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tablon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tablon);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel2.setText("Codigo:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellido:");

        jLabel5.setText("Balance:");

        BTN_Registrar.setText("Registar");
        BTN_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_RegistrarActionPerformed(evt);
            }
        });

        BTN_Modificar.setText("Modificar");
        BTN_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ModificarActionPerformed(evt);
            }
        });

        BTN_Delete.setText("Eliminar");
        BTN_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(INP_Codigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(INP_Nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(INP_Apellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(INP_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTN_Registrar)
                .addGap(18, 18, 18)
                .addComponent(BTN_Modificar)
                .addGap(18, 18, 18)
                .addComponent(BTN_Delete)
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INP_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INP_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INP_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INP_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Delete)
                    .addComponent(BTN_Modificar)
                    .addComponent(BTN_Registrar))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        BTN_Cargar.setText("Cargar");
        BTN_Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CargarActionPerformed(evt);
            }
        });

        BTN_Salir1.setText("Salir");
        BTN_Salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_Salir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(BTN_Cargar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(465, 465, 465)
                        .addComponent(BTN_Salir1)))
                .addContainerGap(484, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 41, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(350, 350, 350)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 41, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(487, Short.MAX_VALUE)
                .addComponent(BTN_Cargar)
                .addGap(44, 44, 44)
                .addComponent(BTN_Salir1)
                .addGap(43, 43, 43))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 83, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 84, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablonMouseClicked
        // TODO add your handling code here:
        try {
            int Fila = Tablon.getSelectedRow ();
            int Ident = Integer.parseInt ( Tablon.getValueAt ( Fila, 0 ).toString () );
            Connection Con = Conecc.getConexion ();
            Stand = Con.prepareStatement ( "SELECT nombre, apellido, balance FROM info_cliente WHERE codigo = ?" );
            Stand.setInt ( 1, Ident );
            RestSet = Stand.executeQuery ();
            while ( RestSet.next () ){
                INP_Codigo.setText ( String.valueOf ( Ident ) );
                INP_Nombre.setText ( RestSet.getString ( "Nombre" ) );
                INP_Apellido.setText ( RestSet.getString ( "Apellido" ) );
                INP_Balance.setText ( String.valueOf ( RestSet.getInt ( "Balance" ) ) );

            }
        } catch ( SQLException e ) {
            JOptionPane.showMessageDialog ( null, e.toString () );
        }
    }//GEN-LAST:event_TablonMouseClicked

    private void BTN_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_RegistrarActionPerformed
        // TODO add your handling code here:
        int Codigo = Integer.parseInt ( INP_Codigo.getText () );
        String Nombre = INP_Nombre.getText ();
        String Apellido = INP_Apellido.getText ();
        int Balance = Integer.parseInt ( INP_Balance.getText () );

        try {
            Connection Con = Conecc.getConexion ();
            Stand = Con.prepareStatement ( "INSERT INTO info_cliente ( codigo, nombre, apellido, balance ) VALUES ( ?, ?, ?, ? )" );
            Stand.setInt ( 1, Codigo );
            Stand.setString ( 2, Nombre );
            Stand.setString ( 3, Apellido );
            Stand.setInt ( 4, Balance );
            Stand.executeUpdate ();
            JOptionPane.showMessageDialog ( null, "Cuenta Registrada." );
            Load ();
            Clean ();
        } catch ( SQLException e ) {
            JOptionPane.showMessageDialog ( null, e.toString () );
        }
    }//GEN-LAST:event_BTN_RegistrarActionPerformed

    private void BTN_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ModificarActionPerformed
        // TODO add your handling code here:
        int Codigo = Integer.parseInt ( INP_Codigo.getText () );
        String Nombre = INP_Nombre.getText ();
        String Apellido = INP_Apellido.getText ();
        int Balance = Integer.parseInt ( INP_Balance.getText () );

        try {
            Connection Con = Conecc.getConexion ();
            Stand = Con.prepareStatement ( "UPDATE info_cliente SET nombre = ?, apellido = ?, balance = ? WHERE codigo = ?" );
            Stand.setString ( 1, Nombre );
            Stand.setString ( 2, Apellido );
            Stand.setInt ( 3, Balance );
            Stand.setInt ( 4, Codigo );
            Stand.executeUpdate ();
            JOptionPane.showMessageDialog ( null, "Cuenta Modificada." );
            Load ();
            Clean ();
        } catch ( SQLException e ) {
            JOptionPane.showMessageDialog ( null, e.toString () );
        }
    }//GEN-LAST:event_BTN_ModificarActionPerformed

    private void BTN_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DeleteActionPerformed
        // TODO add your handling code here:
        int Codigo = Integer.parseInt ( INP_Codigo.getText () );

        try {
            Connection Con = Conecc.getConexion ();
            Stand = Con.prepareStatement ( "DELETE FROM info_cliente WHERE codigo = ?" );
            Stand.setInt ( 1, Codigo );
            Stand.executeUpdate ();
            JOptionPane.showMessageDialog ( null, "Cuenta Eliminada." );
            Load ();
            Clean ();
        } catch ( SQLException e ) {
            JOptionPane.showMessageDialog ( null, e.toString () );
        }
    }//GEN-LAST:event_BTN_DeleteActionPerformed

    private void BTN_CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CargarActionPerformed
        // TODO add your handling code here:
        Load ();
    }//GEN-LAST:event_BTN_CargarActionPerformed

    private void BTN_Salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_Salir1ActionPerformed
        // TODO add your handling code here:
        dispose ();
    }//GEN-LAST:event_BTN_Salir1ActionPerformed

    void Clean () {
        INP_Codigo.setText ( "" );
        INP_Nombre.setText ( "" );
        INP_Apellido.setText ( "" );
        INP_Balance.setText ( "" );
    }

    public void Load () {
        DefaultTableModel Mob = ( DefaultTableModel ) Tablon.getModel ();
        Mob.setRowCount ( 0 );
        int Columna;
        try {
            Connection Con = Conecc.getConexion ();
            Stand = Con.prepareStatement ( "SELECT * FROM info_cliente" );
            RestSet = Stand.executeQuery ();
            Meta = Stand.getMetaData ();
            Columna = Meta.getColumnCount ();
            while ( RestSet.next () ) {
                Object [] Fila = new Object [ Columna ];
                for ( int i = 0; i < Columna; i ++ ){
                    Fila [ i ] = RestSet.getObject ( i + 1 );
                }
                Mob.addRow ( Fila );
            }
        } catch ( SQLException e ) {
            JOptionPane.showMessageDialog ( null, e.toString () );
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Cargar;
    private javax.swing.JToggleButton BTN_Delete;
    private javax.swing.JToggleButton BTN_Modificar;
    private javax.swing.JToggleButton BTN_Registrar;
    private javax.swing.JButton BTN_Salir1;
    private javax.swing.JTextField INP_Apellido;
    private javax.swing.JTextField INP_Balance;
    private javax.swing.JTextField INP_Codigo;
    private javax.swing.JTextField INP_Nombre;
    private javax.swing.JTable Tablon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
