/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD;

import Configuracion_Conexion.Conecc;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class FrmCuenta extends javax.swing.JInternalFrame {

    PreparedStatement Stand;
    ResultSet RestSet;
    ResultSetMetaData Meta;

    /**
     * Creates new form FrmCuenta
     */
    public FrmCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        INP_Cod2 = new javax.swing.JTextField();
        INP_Cod = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        INP_Monto = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        BTN_Salir_Transf11 = new javax.swing.JButton();
        BTN_Modificar = new javax.swing.JToggleButton();

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel16.setText("Transferencia");

        jLabel17.setText("Cuenta Emisora");

        jLabel18.setText("Cuenta Receptora");

        jLabel19.setText("Codigo:");

        jLabel20.setText("Monto:");

        BTN_Salir_Transf11.setText("Salir");
        BTN_Salir_Transf11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_Salir_Transf11ActionPerformed(evt);
            }
        });

        BTN_Modificar.setText("Transferir");
        BTN_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(INP_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INP_Cod2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(BTN_Modificar)
                        .addGap(86, 86, 86)
                        .addComponent(BTN_Salir_Transf11, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(INP_Monto, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(INP_Cod2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(INP_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(INP_Monto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Salir_Transf11)
                    .addComponent(BTN_Modificar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_Salir_Transf11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_Salir_Transf11ActionPerformed
        // TODO add your handling code here:
        dispose ();
    }//GEN-LAST:event_BTN_Salir_Transf11ActionPerformed

    private void BTN_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ModificarActionPerformed
        // TODO add your handling code here:
        Emisor ();
        Receptor ();
        Clean ();
    }//GEN-LAST:event_BTN_ModificarActionPerformed

    void Emisor () {
        int Codigo = Integer.parseInt ( INP_Cod.getText () );
        int Balance = Integer.parseInt ( INP_Monto.getText () );

        try {
            Connection Con = Conecc.getConexion ();
            Stand = Con.prepareStatement ( "UPDATE info_cliente SET balance =  ( SELECT (  balance - ? ) FROM info_cliente WHERE codigo = ? ) WHERE codigo = ?" );
            
            Stand.setInt ( 1, Balance );
            Stand.setInt ( 2, Codigo );
            Stand.setInt ( 3, Codigo );
            Stand.executeUpdate ();
            JOptionPane.showMessageDialog ( null, "Retiro Realizado." );
        } catch ( SQLException e ) {
            JOptionPane.showMessageDialog ( null, e.toString () );
        }
    }
    void Receptor () {
        
        int Codigo = Integer.parseInt ( INP_Cod2.getText () );
        int Balance = Integer.parseInt ( INP_Monto.getText () );
        try {
            Connection Con = Conecc.getConexion ();
            Stand = Con.prepareStatement ( "UPDATE info_cliente SET balance = ( SELECT SUM (  balance + ? ) FROM info_cliente WHERE codigo = ? ) WHERE codigo = ?" );
            
            Stand.setInt ( 1, Balance );
            Stand.setInt ( 2, Codigo );
            Stand.setInt ( 3, Codigo );
            Stand.executeUpdate ();
            JOptionPane.showMessageDialog ( null, "Depsito Realizado." );
        } catch ( SQLException e ) {
            JOptionPane.showMessageDialog ( null, e.toString () );
        }
    
    }
    void Clean () {
        INP_Monto.setText ( "" );
        INP_Cod.setText ( "" );
        INP_Cod2.setText ( "" );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BTN_Modificar;
    private javax.swing.JButton BTN_Salir_Transf11;
    private javax.swing.JTextField INP_Cod;
    private javax.swing.JTextField INP_Cod2;
    private javax.swing.JTextField INP_Monto;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    // End of variables declaration//GEN-END:variables
}
