/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD;


/**
 *
 * @author LENOVO
 */
public class MDIInicio extends javax.swing.JFrame {

    /**
     * Creates new form MDIInicio
     */
    public MDIInicio() {
        initComponents();
        this.setExtendedState ( MAXIMIZED_BOTH );
        this.setTitle ( "Manejo de Cuentas" );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pantalla = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu1 = new javax.swing.JMenu();
        OPEN_FrmCliente = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        OPEN_FrmCuenta = new javax.swing.JMenuItem();
        editMenu1 = new javax.swing.JMenu();
        OPEN_Info = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu1.setMnemonic('f');
        fileMenu1.setText("Cliente");

        OPEN_FrmCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        OPEN_FrmCliente.setMnemonic('x');
        OPEN_FrmCliente.setText("Cliente");
        OPEN_FrmCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPEN_FrmClienteActionPerformed(evt);
            }
        });
        fileMenu1.add(OPEN_FrmCliente);

        menuBar.add(fileMenu1);

        editMenu.setMnemonic('e');
        editMenu.setText("Transferencia");

        OPEN_FrmCuenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        OPEN_FrmCuenta.setMnemonic('d');
        OPEN_FrmCuenta.setText("Transferir");
        OPEN_FrmCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPEN_FrmCuentaActionPerformed(evt);
            }
        });
        editMenu.add(OPEN_FrmCuenta);

        menuBar.add(editMenu);

        editMenu1.setMnemonic('e');
        editMenu1.setText("About");

        OPEN_Info.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        OPEN_Info.setText("Info");
        OPEN_Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPEN_InfoActionPerformed(evt);
            }
        });
        editMenu1.add(OPEN_Info);

        menuBar.add(editMenu1);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        aboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Manual");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 1220, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OPEN_FrmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPEN_FrmClienteActionPerformed
        FrmCliente Show = new FrmCliente ();
        Pantalla.add ( Show );
        Show.setVisible ( true );
        Show.toFront ();
        Show.show ();
    }//GEN-LAST:event_OPEN_FrmClienteActionPerformed

    private void OPEN_InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPEN_InfoActionPerformed
        // TODO add your handling code here:
        FrmBanco Show = new FrmBanco ();
        Pantalla.add ( Show );
        Show.setVisible ( true );
        Show.toFront ();
        Show.show ();
    }//GEN-LAST:event_OPEN_InfoActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        FrmCuentasBancos Show = new FrmCuentasBancos ();
        Pantalla.add ( Show );
        Show.setVisible ( true );
        Show.toFront ();
        Show.show ();
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void OPEN_FrmCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPEN_FrmCuentaActionPerformed
        // TODO add your handling code here:
        FrmCuenta Show = new FrmCuenta ();
        Pantalla.add ( Show );
        Show.setVisible ( true );
        Show.toFront ();
        Show.show ();
    }//GEN-LAST:event_OPEN_FrmCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem OPEN_FrmCliente;
    private javax.swing.JMenuItem OPEN_FrmCuenta;
    private javax.swing.JMenuItem OPEN_Info;
    private javax.swing.JDesktopPane Pantalla;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu editMenu1;
    private javax.swing.JMenu fileMenu1;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
